import prisma from "./PrismaClient";
import rn from "random-number";
async function main() {
  const carData = [
    {
      id: "clu4cn6si0000lqsdbg41xm8i",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2020_jaguar_xe_reims_edition_5_2560x1440.webp",
    },
    {
      id: "clu4cn6si0001lqsdwwb933d1",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2021_jaguar_f-pace_1_2560x1440.webp",
    },
    {
      id: "clu4cn6si0002lqsdo0ee2xyu",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2021_jaguar_xf_sportbrake_3_2560x1440.webp",
    },
    {
      id: "clu4cn6si0003lqsdxg2rxa0g",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2021_koenigsegg_gemera_1_2560x1440.webp",
    },
    {
      id: "clu4cn6si0004lqsdqc5yofo3",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2023-McLaren-Artura-GT4---Front-Three-Quarter-3851496-2560x1440.webp",
    },
    {
      id: "clu4cn6si0005lqsd71sd7kba",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_alfa_romeo_stelvio_3_2560x1440.webp",
    },
    {
      id: "clu4cn6si0006lqsdaqhxw962",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_alfa_romeo_tonale_2_2560x1440.webp",
    },
    {
      id: "clu4cn6si0007lqsdeusm2k4v",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_bentley_continental_gt_s_1_2560x1440.webp",
    },
    {
      id: "clu4cn6si0008lqsdhim1wbcm",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_bentley_mulliner_batur_2_2560x1440.webp",
    },
    {
      id: "clu4cn6si0009lqsdr92ma0v6",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_brabus_900_rocket_r_1_of_25_1_2560x1440.webp",
    },
    {
      id: "clu4cn6si000alqsdyjrepcut",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_brabus_mercedes-amg_g_63_4x4_2_1_2560x1440.webp",
    },
    {
      id: "clu4cn6si000blqsduchecxdg",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2023_bugatti_chiron_super_sport_golden_era_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000clqsd3hri3w81",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_bugatti_w16_mistral_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000dlqsdsbzfcyxa",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_koenigsegg_cc850_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000elqsdrju2vhoz",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2023_lamborghini_urus_performante_polizia_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000flqsd7q2pma7h",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2023_lexus_ux_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000glqsd1zioe6m9",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2024-McLaren-750S-with-3-7-59-Theme---Top-3879465-2560x1440.webp",
    },
    {
      id: "clu4cn6sj000hlqsdlwome13l",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2024-McLaren-GTS---Front-Three-Quarter-3879478-2560x1440.webp",
    },
    {
      id: "clu4cn6sj000ilqsdo7kau8gb",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2024-Mercedes-Benz-E-Class-Plug-In-Hybrid-AMG-Line-Color-(Verde-Silver)---Front-3869660-2560x1440.webp",
    },
    {
      id: "clu4cn6sj000jlqsdyixctua2",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2024-Mercedes-Benz-G-500-Final-Edition---Front-Three-Quarter-3872343-2560x1440.webp",
    },
    {
      id: "clu4cn6sj000klqsd48v44ytz",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_alfa_romeo_33_stradale_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000llqsdccavja5s",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2024_alfa_romeo_stelvio_quadrifoglio_100th_anniversary_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000mlqsddxqm1jlt",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_aston_martin_db12_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000nlqsd5ie4w5l4",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_aston_martin_dbs_770_ultimate_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000olqsdjlmvnwqx",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_aston_martin_vantage_gt3_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000plqsdcno73b3f",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_aston_martin_vantage_gt4_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000qlqsdls06azyc",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_audi_rs_7_performance_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000rlqsd41cyq617",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_ferrari_296_challenge_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000slqsdzyuw6vi6",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_ferrari_sf90_xx_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000tlqsd7j9ti8dt",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_ferrari_sp-8_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000ulqsdrytuzetx",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_lamborghini_huracan_sterrato_3_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000vlqsdh0nakf7p",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_lamborghini_revuelto_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000wlqsdhoidmw1j",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_lexus_lbx_morizo_rr_concept_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000xlqsdf434u4am",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_lexus_lc_500_inspiration_series_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000ylqsdr70nwup8",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_range_rover_evoque_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj000zlqsdxahqweh1",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2024_range_rover_velar_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj0010lqsdej2ozfvs",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl:
        "cars/2025-Mercedes-AMG-GLC-63-S-E-PERFORMANCE-(Color-Spectral-Blue-Metallic)---Front-Three-Quarter-3877616-2560x1440.webp",
    },
    {
      id: "clu4cn6sj0011lqsd5lzvsn4f",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2025_aston_martin_vantage_11_2560x1440.webp",
    },
    {
      id: "clu4cn6sj0012lqsdezhu46y6",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2025_audi_a3_allstreet_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj0013lqsdpevcbtkt",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2025_audi_a3_sportback_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj0014lqsds26bzx7n",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2025_audi_q7_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj0015lqsdqop7x501",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2025_audi_sq7_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj0016lqsd6dm3pp6k",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2025_ram_1500_ramcharger_1_2560x1440.webp",
    },
    {
      id: "clu4cn6sj0017lqsdwdbwa8q9",
      name: "koenigsegg Gemera",
      year: 2023,
      model: "Gemera",
      manufacturer: "koenigsegg",
      gearType: "AT",
      fuelType: "PETROL",
      fuelcapacity: 75,
      seats: 2,
      carType: "SEDAN",
      description:
        "The Gemera is the first four-seater car built by Koenigsegg. Its also\n      powered by a compact engine weighing only 70 kg (150 lb). The engine\n      is so small because it is a camless piston engine, the first such\n      engine announced for a production car.",
      city: "BIJAPUR",
      state: "KARNATAKA",
      country: "INDIA",
      baseUrl: "https://d38vo1rzl5mxfz.cloudfront.net/",
      imageUrl: "cars/2025_ram_1500_rev_1_2560x1440.webp",
    },
  ];
  carData.forEach(async (eachCar) => {
    const rentalPrice = rn({
      min: 100,
      max: 120,
      integer: true,
    });

    const perkm = parseFloat((rentalPrice / 300).toFixed(2));

    const CITIES = [
      "Keerti Nagar",
      "Adarsh Nagar",
      "Ram Nagar",
      "Ganesh Nagar",
      "Sai Park",
    ];
    const selectCity = rn({
      min: 0,
      max: 4,
      integer: true,
    });

    const {
      id,
      name,
      year,
      model,
      manufacturer,
      fuelcapacity,
      seats,
      description,
      state,
      country,
      baseUrl,
      imageUrl,
    } = eachCar;
    const result = await prisma.car.upsert({
      where: { id: "" },
      update: {},
      create: {
        name,
        year,
        model,
        manufacturer,
        fuelcapacity,
        seats,
        description,
        city: CITIES[selectCity],
        state,
        country,
        baseUrl,
        imageUrl,
        price: {
          create: {
            offerPrice: rn({
              min: 70,
              max: 80,
              integer: true,
            }),
            rentalPrice: rentalPrice,
            perKilometerCost: perkm,
          },
        },
        availability: {
          create: {
            currentLocation: CITIES[selectCity],
          },
        },
      },
    });

    console.log(result);
  });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
